<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>MSCaddie.Shared</PackageId>
    <Version>1.0.0</Version>
    <Authors>Paul S</Authors>
    <Company>PaulS</Company>
    <Description>Interfaces and shared models for the MSCaddie.Repository</Description>
    <PackageTags>utilities;tools</PackageTags>
    <RepositoryUrl>https://github.com/paulsoerensen/repo</RepositoryUrl>
    <PackageOutputPath>c:\Projects\LocalPackages</PackageOutputPath>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Blazored.SessionStorage" Version="2.4.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>
 
</Project>
