name: Build project and deploy to FTP server
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build package and deploy to FTP server
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet restore MSCaddie/MSCaddie.csproj --runtime win-x86

      - name: Debug secret (not recommended for real secrets)
        run: echo ${{ secrets.PAULSWEB_USER }} | sed 's/./& /g'

      - name: Debug secret (not recommended for real secrets)
        run: echo ${{ secrets.PAULSWEB_PWD }}| sed 's/./& /g'

      - name: Debug secret (not recommended for real secrets)
        run: echo ${{ secrets.PAULSWEB_URL }}| sed 's/./& /g'

      - name: Publish
        shell: bash
        run: |
          dotnet publish MSCaddie/MSCaddie.csproj \
            --configuration Release \
            --framework net8.0 \
            --output publish \
            --runtime win-x86 \
            --no-restore \
            --self-contained true \
            -p:PublishTrimmed=false \
            -p:PublishSingleFile=false

      - name: Deploy to Simply
        uses: rasmusbuchholdt/simply-web-deploy@2.2.0
        with:
          website-name: 'paulsweb.dk'
          server-computer-name: 'https://nt7.unoeuro.com:8172'
          server-username: 'paulsweb.dk'
          server-password: ${{ secrets.PAULSWEB_PWD }}
          source-path: 'publish'
          target-path: '/admin/'

