name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'   # Publish only when you push a version tag like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Show variables
      run: |
        echo "Actor: ${{ github.actor }}"
        echo "Owner: ${{ github.repository_owner }}"
        echo "Token length: ${#GITHUB_TOKEN}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Checkout repository
      uses: actions/checkout@v4
