name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'   # Publish only when you push a version tag like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Show NuGet config
      run: dotnet nuget list source --verbosity detailed
      shell: bash
